// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyxzjsbyolnzbadtmrew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5eHpqc2J5b2xuemJhZHRtcmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjE1NjEsImV4cCI6MjA3MDI5NzU2MX0.YDBiNVO_r3a-4eDCDruYd_pEaJlRjBtuncLdFByJnT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});